Split facts and assumptions
GermanZero-de/localzero-generator-core pull request #346
Opened 2023-05-24 22:00 UTC by Jeniffere

Facts and assumptions are already separate files in data.
Now facts and assumptions are also separate in the code.
As a next step I can pass facts/assumptions/entries to several functions instead of the whole inputs

python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.301 -> v1.1.309).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at E:\LocalZero\Code\main\localzero-generator-core.
Loading pyproject.toml file at E:\LocalZero\Code\main\localzero-generator-core\pyproject.toml
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 172 source files
pyright 1.1.301
0 errors, 0 warnings, 0 informations
Completed in 10.051sec
==================================================================== test session starts ===================================================================== 
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: E:\LocalZero\Code\main\localzero-generator-core
plugins: cov-3.0.0
collected 39 items

tests\test_devtool_commands.py ..............                                                                                                           [ 35%] 
tests\test_end_to_end.py ...........                                                                                                                    [ 64%] 
tests\test_entries.py .                                                                                                                                 [ 66%] 
tests\test_refdata.py ....                                                                                                                              [ 76%] 
tests\test_tracing.py .........                                                                                                                         [100%] 

==================================================================== 39 passed in 17.55s ===================================================================== 
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at cf38666afa6fe306beb27e6422af5ce31c707f7d, but don't forget to copy paste the above into your pull request

2023-06-12 18:46 UTC, bgrundmann requested changes

2023-06-12 18:46 UTC, bgrundmann commented on commands/cmd_data.py
I'm not that happy about the code duplication we know have (`lookup_fact` / `lookup_ass`).  You could pull 

```python
# move this into cmd_data_lookup
data = ref_data.RefData.load() 
# and then call either
lookup_and_print(pattern, "fact", data.facts().complete_fact)
# or depending on the pattern
lookup_and_print(pattern, "assumption", data.assumptions().complete_ass)

# and merge lookup_fact / lookup_ass back into lookup_fact_or_ass
# the type of the callable changes slightly as it class will already be bound.
# so out of the top of my head it should be
def lookup_and_print(pattern: str, what: Literal["fact", "assumption"], lookup: Callable[[str], refdata.FactOrAssumptionCompleteRow]):
   ...

```
But maybe I missed something? Or you did that on purpose because you want to make bigger changes?

2023-06-12 18:46 UTC, bgrundmann commented on src/climatevision/generator/entries.py
> +# pyright: strict
This is a good change. I like this.

2023-06-13 19:50 UTC, Jeniffere commented on commands/cmd_data.py
@bgrundmann:

Good point ... this code duplication is bad.

In a previous commit I removed the dataclass FactsAndAssumptions. I think your proposal maybe needs this dataclass.

Anyway I implemented antoher solution to remove the code duplication. What do you think about that?

2023-06-19 08:36 UTC, bgrundmann commented on commands/cmd_data.py
I don't think it does actually because python has typing.Union (aka TypeFoo | TypeBar). But your new solution is maybe even better.

I took the liberty of adding a few more specific types to get rid of some of the Any. But I like it all.

2023-06-19 08:38 UTC, bgrundmann approved these changes

2023-06-19 08:38 UTC, bgrundmann commented
Here is the updated ready to rock:

```
(.venv) benediktgrundmann@Benedikts-Air localzero-generator-core % python devtool.py ready_to_rock
WARNING: there is a new pyright version available (v1.1.301 -> v1.1.314).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`

No configuration file found.
pyproject.toml file found at /Users/benediktgrundmann/Programming/localzero/localzero-generator-core.
Loading pyproject.toml file at /Users/benediktgrundmann/Programming/localzero/localzero-generator-core/pyproject.toml
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Searching for source files
Found 172 source files
pyright 1.1.301
0 errors, 0 warnings, 0 informations
Completed in 2.126sec
=========================================================== test session starts ============================================================
platform darwin -- Python 3.10.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/benediktgrundmann/Programming/localzero/localzero-generator-core
plugins: anyio-3.6.2, cov-3.0.0
collected 39 items

tests/test_devtool_commands.py ..............                                                                                        [ 35%]
tests/test_end_to_end.py ...........                                                                                                 [ 64%]
tests/test_entries.py .                                                                                                              [ 66%]
tests/test_refdata.py ....                                                                                                           [ 76%]
tests/test_tracing.py .........                                                                                                      [100%]

============================================================ 39 passed in 5.48s ============================================================
Trim Trailing Whitespace.................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Don't commit to branch...................................................Passed
black....................................................................Passed
You are ready to rock and save the climate at ac5d7d4c46502cc8e655226e7c83be9627d7e304, but don't forget to copy paste the above into your pull request
```

2023-06-19 08:39 UTC, merged